name: Desplegar a Pruebas

on:
  push:
    branches:
      - pruebas

jobs:
  deploy_pruebas:
    runs-on: ubuntu-latest
    steps:
      - name: Bajar el c√≥digo
        uses: actions/checkout@v4

      - name: Desplegar a Firebase Hosting (Sitio de Pruebas)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_TOKEN }}'
          channelId: live 
          projectId: gad-alicante-v1
          target: gad-alicante-pruebas
