name: Desplegar a Pruebas (MANUAL)

on:
  push:
    branches:
      - pruebas

jobs:
  deploy_pruebas:
    runs-on: ubuntu-latest
    steps:
      - name: Bajar el c√≥digo
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar Firebase y Desplegar
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          npm install -g firebase-tools
          firebase deploy --only hosting:gad-alicante-pruebas --project gad-alicante-v1 --token "$FIREBASE_TOKEN" --non-interactive
