name: Desplegar a Pruebas

on:
  push:
    branches:
      - pruebas

jobs:
  deploy_pruebas:
    runs-on: ubuntu-latest
    steps:
      - name: Bajar el c√≥digo
        uses: actions/checkout@v4

      - name: Instalar y Desplegar
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:gad-alicante-pruebas --project gad-alicante-v1
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
